# This is a basic workflow to help you get started with Actions

name: CI
on:
workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
        
  DevTeste:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, DEVTESTE
               
